### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by MerliX** [grimalschi/calque#1]
Interesting tool, but I didn't find sign to comment line.
When you do many calculations, comments will help you understand what's happening

**Comment by josdejong** [comment]
You can use the `#` character to start a comment

**Comment by MerliX** [comment]
@josdejong I see error
<img width="691" alt="screenshot 2015-08-06 01 36 11" src="https://cloud.githubusercontent.com/assets/988869/9097228/b2de4198-3bdb-11e5-98b3-4db2122b2e71.png">

**Comment by josdejong** [comment]
That's something calque should handle. The used expression parser (math.js) returns `undefined` in case of an empty expression, and `undefined` does not have a method `toString()`, hence the error message

``` js
math.eval('');               // returns undefined
math.eval('# some comment'); // returns undefined
```

**Comment by grimalschi** [comment]
Fixed
