### ISSUE TITLE
problem with comments and strings literals

### ISSUE THREAD

**Issue by ruv** [grimalschi/calque#12]
It seems that contents of the comments and string literals have some side effect.

The testcase for comments:

```
#  = r*tan(a) = tan(a)
tan(0)
```

The testcase for strings:

```
x= " = r*tan(a) = tan(a)"
tan(0)
```

Expected result: `= 0`
Actual result: `// Error: Undefined symbol r`
(in the both cases)

Perhaps there is need  a proper parser instead of [plain text processing](https://github.com/grimalschi/calque/blob/88062d5adb953f1b9b95e51382c1e0afd839d6e1/calque.js#L80).

**Comment by grimalschi** [comment]
Fixed
