### ISSUE TITLE
Function "pow2" doesn't work

### ISSUE THREAD

**Issue by arthrp** [grimalschi/calque#6]
In examples you use e.g.

> pow2(6)

which isn't a valid function. pow(x,2) seems to work, though. Is "pow2" in examples a typo?

**Comment by josdejong** [comment]
The pow2 shows how to define a new function yourself:

```
pow2(x) = x ^ 2   # define a new function
pow2(6)           # use the function
```

**Comment by arthrp** [comment]
Point taken. Sorry for my lack of attention :)
